// <auto-generated />
using System;
using ChatrDate.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ChatrDate.Migrations
{
    [DbContext(typeof(AddaptAppDatingAPIContext))]
    [Migration("20210914145414_UpdateVisitors")]
    partial class UpdateVisitors
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:Collation", "Latin1_General_CI_AS")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ChatrDate.Models.Visitors", b =>
                {
                    b.Property<int>("VisitorId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VisitorCount")
                        .HasColumnType("int");

                    b.HasKey("VisitorId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Visitors");
                });

            modelBuilder.Entity("ChatrDate.Models.Visitors", b =>
                {
                    b.HasOne("ChatrDate.Models.User", "Visitores")
                        .WithMany("ViewVisitors")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ChatrDate.Models.User", "Visitor")
                        .WithMany("Visitores")
                        .HasForeignKey("VisitorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Visitor");

                    b.Navigation("Visitores");
                });

#pragma warning restore 612, 618
        }
    }
}
